[project]
name = "mplutils"
version = "0.6.0"
authors = [{ name = "Max Kircher" }]
description = """
    A collection of utility methods to manipulate matplotlib figures.
"""
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["numpy", "matplotlib"]

[project.urls]
"Repository" = "https://github.com/frekm/mpl-utils"
"Documentation" = "https://mpl-utils.readthedocs.io/en/latest/"

[dependency-groups]
dev = [
    "intersphinx-registry>=0.2605.27",
    "mplutils",
    "numpydoc>=1.10.0",
    "pydata-sphinx-theme>=0.17.1",
    "sphinx>=9.0.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mplutils"]

[tool.ruff]
line-length = 88
fix = true

[tool.ruff.lint]
extend-select = ["NPY", "I", "RUF022"]
